/*
 * Ember API
 *
 * Comprehensive specifications for all Ember API endpoints, incorporating the complete set of DeFi capabilities.
 *
 * The version of the OpenAPI document: 0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BorrowTokensRequest {
    #[serde(rename = "fromAddress")]
    pub from_address: String,
    #[serde(rename = "protocol")]
    pub protocol: String,
    #[serde(rename = "collateralToken")]
    pub collateral_token: String,
    #[serde(rename = "collateralAmount")]
    pub collateral_amount: String,
    #[serde(rename = "borrowToken")]
    pub borrow_token: String,
    #[serde(rename = "borrowAmount")]
    pub borrow_amount: String,
    #[serde(rename = "interestRateMode")]
    pub interest_rate_mode: InterestRateMode,
    #[serde(rename = "maxFee")]
    pub max_fee: String,
}

impl BorrowTokensRequest {
    pub fn new(from_address: String, protocol: String, collateral_token: String, collateral_amount: String, borrow_token: String, borrow_amount: String, interest_rate_mode: InterestRateMode, max_fee: String) -> BorrowTokensRequest {
        BorrowTokensRequest {
            from_address,
            protocol,
            collateral_token,
            collateral_amount,
            borrow_token,
            borrow_amount,
            interest_rate_mode,
            max_fee,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InterestRateMode {
    #[serde(rename = "VARIABLE")]
    Variable,
    #[serde(rename = "STABLE")]
    Stable,
}

impl Default for InterestRateMode {
    fn default() -> InterestRateMode {
        Self::Variable
    }
}

