/*
 * Ember API
 *
 * Comprehensive specifications for all Ember API endpoints, incorporating the complete set of DeFi capabilities.
 *
 * The version of the OpenAPI document: 0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LendTokensRequest {
    #[serde(rename = "fromAddress")]
    pub from_address: String,
    #[serde(rename = "protocol")]
    pub protocol: String,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "interestRateMode")]
    pub interest_rate_mode: InterestRateMode,
    #[serde(rename = "enableCollateral")]
    pub enable_collateral: bool,
    #[serde(rename = "maxFee")]
    pub max_fee: String,
}

impl LendTokensRequest {
    pub fn new(from_address: String, protocol: String, token: String, amount: String, interest_rate_mode: InterestRateMode, enable_collateral: bool, max_fee: String) -> LendTokensRequest {
        LendTokensRequest {
            from_address,
            protocol,
            token,
            amount,
            interest_rate_mode,
            enable_collateral,
            max_fee,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InterestRateMode {
    #[serde(rename = "VARIABLE")]
    Variable,
    #[serde(rename = "STABLE")]
    Stable,
}

impl Default for InterestRateMode {
    fn default() -> InterestRateMode {
        Self::Variable
    }
}

