/*
 * Ember API
 *
 * Comprehensive specifications for all Ember API endpoints, incorporating the complete set of DeFi capabilities.
 *
 * The version of the OpenAPI document: 0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemoveLiquidityRequest {
    #[serde(rename = "fromAddress")]
    pub from_address: String,
    #[serde(rename = "protocol")]
    pub protocol: String,
    #[serde(rename = "positionId")]
    pub position_id: String,
    #[serde(rename = "percentage")]
    pub percentage: i32,
    #[serde(rename = "maxFee")]
    pub max_fee: String,
    #[serde(rename = "recipient", skip_serializing_if = "Option::is_none")]
    pub recipient: Option<String>,
}

impl RemoveLiquidityRequest {
    pub fn new(from_address: String, protocol: String, position_id: String, percentage: i32, max_fee: String) -> RemoveLiquidityRequest {
        RemoveLiquidityRequest {
            from_address,
            protocol,
            position_id,
            percentage,
            max_fee,
            recipient: None,
        }
    }
}

