/*
 * Ember API
 *
 * Comprehensive specifications for all Ember API endpoints, incorporating the complete set of DeFi capabilities.
 *
 * The version of the OpenAPI document: 0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RepayBorrowedTokensRequest {
    #[serde(rename = "fromAddress")]
    pub from_address: String,
    #[serde(rename = "protocol")]
    pub protocol: String,
    #[serde(rename = "borrowPositionId")]
    pub borrow_position_id: String,
    #[serde(rename = "borrowToken")]
    pub borrow_token: String,
    #[serde(rename = "repayAmount")]
    pub repay_amount: String,
    #[serde(rename = "interestRateMode")]
    pub interest_rate_mode: InterestRateMode,
    #[serde(rename = "maxFee")]
    pub max_fee: String,
}

impl RepayBorrowedTokensRequest {
    pub fn new(from_address: String, protocol: String, borrow_position_id: String, borrow_token: String, repay_amount: String, interest_rate_mode: InterestRateMode, max_fee: String) -> RepayBorrowedTokensRequest {
        RepayBorrowedTokensRequest {
            from_address,
            protocol,
            borrow_position_id,
            borrow_token,
            repay_amount,
            interest_rate_mode,
            max_fee,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InterestRateMode {
    #[serde(rename = "VARIABLE")]
    Variable,
    #[serde(rename = "STABLE")]
    Stable,
}

impl Default for InterestRateMode {
    fn default() -> InterestRateMode {
        Self::Variable
    }
}

