/*
 * Ember API
 *
 * Comprehensive specifications for all Ember API endpoints, incorporating the complete set of DeFi capabilities.
 *
 * The version of the OpenAPI document: 0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitTransactionRequest {
    #[serde(rename = "fromAddress")]
    pub from_address: String,
    #[serde(rename = "signedTransaction")]
    pub signed_transaction: String,
    #[serde(rename = "protocol")]
    pub protocol: String,
}

impl SubmitTransactionRequest {
    pub fn new(from_address: String, signed_transaction: String, protocol: String) -> SubmitTransactionRequest {
        SubmitTransactionRequest {
            from_address,
            signed_transaction,
            protocol,
        }
    }
}

