/*
 * Ember API
 *
 * Comprehensive specifications for all Ember API endpoints, incorporating the complete set of DeFi capabilities.
 *
 * The version of the OpenAPI document: 0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationErrorErrorValidationErrorsInner {
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "errorCode")]
    pub error_code: String,
}

impl ValidationErrorErrorValidationErrorsInner {
    pub fn new(field: String, message: String, error_code: String) -> ValidationErrorErrorValidationErrorsInner {
        ValidationErrorErrorValidationErrorsInner {
            field,
            message,
            error_code,
        }
    }
}

