/*
 * Ember API
 *
 * Comprehensive specifications for all Ember API endpoints, incorporating the complete set of DeFi capabilities.
 *
 * The version of the OpenAPI document: 0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WithdrawalDetailsToken1 {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "amount")]
    pub amount: String,
}

impl WithdrawalDetailsToken1 {
    pub fn new(address: String, amount: String) -> WithdrawalDetailsToken1 {
        WithdrawalDetailsToken1 {
            address,
            amount,
        }
    }
}

