
name: Server Deployment

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'openapi-spec.yaml'

jobs:
  push_latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install OpenAPI generator CLI
        run: |
          pnpm add -g @openapitools/openapi-generator-cli

      - name: Update autogenerator code
        run: |
          openapi-generator-cli list
